### ISSUE TITLE
Maven central deploy?

### ISSUE THREAD

**Issue by wildone** [websight-io/howlite#296]
Is it possible to pull dependency to this via maven central?

1.0.1 works but latest does not, access denied.

```
      <dependency>
        <groupId>pl.ds.howlite</groupId>
        <artifactId>howlite-core</artifactId>
        <version>1.0.3</version>
        <scope>provided</scope>
      </dependency>
```

**Comment by paweljozwicki** [comment]
Hi, we don't have the 1.0.3 version released yet. In the repository, it's a SNAPSHOT and at least for now, we don't want to release SNAPSHOT versions.
